### ISSUE TITLE
Additional information for gamedeals command

### ISSUE THREAD

**Issue by t-vaudry** [darrenfoley/Asiago#13]
When using /gamedeals provide a note about whether the seller provides a Steam code for the game or not. Optionally, does it provide a code for other game systems (ie. Epic Games, etc.)

**Comment by darrenfoley** [comment]
From what I can see, there's currently no reliable way of getting this info from IsThereAnyDeal. There's a DRM field, but it doesn't seem reliable, especially since there are steam games without steam DRM and GOG games don't have DRM.

If there's some way I've missed, it could be looked at when the IsThereAnyDeal stuff is rewritten for their new API.

Their new API docs are here: https://docs.isthereanydeal.com/

Closing for now
